#!/usr/bin/env python
#
#	pypaxctl: this file is part of the elfix package
#	Copyright (C) 2011  Anthony G. Basile
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


import sys
import getopt
import pax

def main():
	try:
		opts, args = getopt.getopt(sys.argv[1:], 's:g')
	except getopt.GetoptError as err:
		print(err)
		sys.exit(1)

	if len(opts) == 0:
		print('Provide either -s <flags> <elf> xor -g <elf>')
		sys.exit(1)

	binary = None

	do_set = 0
	do_get = 0

	for o, a in opts:
		if o == '-s':
			flags = a
			do_set = 1
		elif o == '-g':
			do_get = 1

	if( (do_set + do_get) != 1 ):
		print('Provide either -s <flags> <elf> xor -g <elf>')
		sys.exit(1)

	if( len(args) < 1 ):
		print('Provide either -s <flags> <elf> xor -g <elf>')
		sys.exit(1)

	if( do_set == 1 ):
		for binary in args:
			pax.setstrflags(binary, flags)
	else:
		for binary in args:
			( str_flags, bin_flags ) = pax.getflags(binary)
			print('%s' % str_flags)

if __name__ == '__main__':
	main()
