#!/usr/bin/env python

import sys
import getopt
import pax

def main():
	try:
		opts, args = getopt.getopt(sys.argv[1:], 's:g')
	except getopt.GetoptError as err:
		print(err)
		sys.exit(1)

	if len(opts) == 0:
		print('Provide either -s <flags> <elf> xor -g <elf>')
		sys.exit(1)

	binary = None

	do_set = 0
	do_get = 0

	for o, a in opts:
		if o == '-s':
			#pax.setflags(a, flags)
			flags = a
			do_set = 1
		elif o == '-g':
			#( str_flags, bin_flags ) = pax.getflags(a)
			do_get = 1

	if( (do_set + do_get) != 1 ):
		print('Provide either -s <flags> <elf> xor -g <elf>')
		sys.exit(1)

	if( len(args) < 1 ):
		print('Provide either -s <flags> <elf> xor -g <elf>')
		sys.exit(1)

	if( do_set == 1 ):
		for binary in args:
			print('set %s on %s' % (flags,binary))
	else:
		for binary in args:
			print('get on %s' % binary)

if __name__ == '__main__':
	main()
